[project]
name = "hanzo-studio-node" # unique namespace for the node pack
version = "0.1.0"
description = "Hanzo Studio Node that does"
authors = [
  {name = "", email = ""}
]
readme = "README.md"
license = {file = "LICENSE"}
dependencies = []

[project.urls]
bugs = ""
homepage = ""
repository = ""


[tool.comfy]
PublisherId = "" # Registry ID
DisplayName = "" # Display Name for Hanzo Registry
Icon = "" # Icon URL for Hanzo Registry
